### ISSUE TITLE
TypeError: text.replace is not a function

### ISSUE THREAD

**Issue by askemeline** [regar007/react-native-markdown-formatter#1]
Hello, first of all, thanks for your project it's very cool!

I would like to custom, so I follow and and add customMarkdownFormatterRegex, but I got an error

```TypeError: text.replace is not a function. (In 'text.replace(parsed[0], parsed[1] + spacesStr), 'text.replace' is undefined)```

Do you know how to fix it ? thanks

**Comment by askemeline** [comment]
It was my mistake, I add styles in defaultStyles like defaultStyles={styles.description}
I delete it and it's work well thanks :)

**Comment by regar007** [comment]
cool. glad to hear you worked it out. 👍
- Ashok,
